import { listSources } from '../store/sources.js';

/**
 * Optional go2rtc normalization layer.
 *
 * By default the CV sidecar pulls a clip directly from each camera's resolved
 * URL, so go2rtc is NOT required. For feeds the sidecar can't decode directly
 * (auth quirks, odd codecs, YouTube-live needing yt-dlp), put go2rtc in front:
 * it restreams everything as uniform HLS/MP4 the sidecar can fetch at
 * `${GO2RTC_URL}/api/stream.mp4?src=<sourceId>`.
 *
 * This generates a go2rtc.yaml `streams` map from the registered camera sources.
 */
const CAMERA_KINDS = new Set(['webcam', 'ip_camera', 'traffic_cam', 'weather_cam']);

export interface Go2rtcStream {
  sourceId: string;
  name: string;
  spec: string;
}

export async function buildGo2rtcStreams(): Promise<Go2rtcStream[]> {
  const sources = await listSources();
  const streams: Go2rtcStream[] = [];

  for (const s of sources) {
    if (!s.enabled) continue;
    const cfg = s.config as Record<string, unknown>;
    const url = String(cfg.streamUrl ?? cfg.url ?? '');
    const streamType = String(cfg.streamType ?? 'image');
    const sid = String(cfg.sourceId ?? s.id);

    if (s.kind === 'youtube' && streamType === 'youtube') {
      // go2rtc resolves YouTube live via its yt-dlp helper.
      streams.push({ sourceId: sid, name: s.name, spec: url });
      continue;
    }
    if (!CAMERA_KINDS.has(s.kind)) continue;
    if (!url || !(url.startsWith('http') || url.startsWith('rtsp'))) continue;
    // Static-jpeg refresh cams have no continuous stream — skip (single-frame path).
    if (streamType === 'image') continue;

    streams.push({ sourceId: sid, name: s.name, spec: url });
  }
  return streams;
}

/** Render a minimal go2rtc.yaml. Hand-formatted to avoid a YAML dependency. */
export async function renderGo2rtcConfig(apiPort = 1984): Promise<string> {
  const streams = await buildGo2rtcStreams();
  const lines: string[] = ['# Generated by samaritan-feeder — go2rtc stream map', 'api:', `  listen: ":${apiPort}"`, 'streams:'];
  if (streams.length === 0) {
    lines.push('  # (no continuous camera streams registered)');
  }
  for (const s of streams) {
    // Quote the URL; go2rtc accepts a bare URL or a typed source string.
    lines.push(`  ${yamlKey(s.sourceId)}: ${JSON.stringify(s.spec)}`);
  }
  return lines.join('\n') + '\n';
}

function yamlKey(k: string): string {
  return /^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k);
}
